/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import com.intuit.karate.Results;
import com.intuit.karate.Runner;
import org.junit.jupiter.api.Test;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ParallelTest {

        @Test
        void testParallel() {
            Results results = Runner.path("classpath:com/api/test/features").parallel(4);
            assertEquals(0, results.getFailCount(), results.getErrorMessages());
        }

    }

